name: complimentary_colors
version: 1.0.2
author: Matt Miller <matt@megamattmiller.com>
description: An easy to use Dart package for calculating complimentary colors.
homepage: https://github.com/MegaMattMiller/complimentary_colors

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  color: ^2.1.1

dev_dependencies:
  test: ^1.5.3