name: complimentary_colors
version: 0.0.5
author: Matt Miller <matt@megamattmiller.com>
description: An easy to use Dart package for calculating complimentary colors.
homepage: https://github.com/MegaMattMiller/complimentary_colors

environment:
  sdk: any

dependencies:
  color: ">=2.0.2 <3.0.0"

dev_dependencies:
  test: ">=0.12.34 < 1.0.0"