name: complimentary_colors
version: 1.0.3
description: An easy to use Dart package for calculating complimentary colors.
homepage: https://github.com/MegaMattMiller/complimentary_colors

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  color: ^2.1.1

dev_dependencies:
  test: ^1.11.1
  pedantic: ^1.9.0