name: complimentary_colors
version: 0.0.1
author: Matt Miller
description: A package containing useful, reuseable classes that can be used in any Dart project.
homepage: https://github.com/MegaMattMiller/complimentary_colors

environment:
  sdk: any

dependencies:
  color: any
  test: "^0.12.34"

dev-dependencies:
  